version: '3.8'

services:
  redis:
    image: redis:latest@sha256:6aafb7f25fc93c4ff74e99cff8e85899f03901bc96e61ba12cd3c39e95503c73
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    container_name: unixbot
    environment:
      - REDIS_HOST=redis
      - TWITTER_USERNAME=bot_unixporn
      - TWITTER_PASSWORD=strongPassword
      - REDDIT_USERNAME=bot_unixporn
      - REDDIT_PASSWORD=strongPassword
      - REDDIT_CLIENT_ID=client_id
      - REDDIT_CLIENT_SECRET=client_secret
    depends_on:
      - redis