version: '3.8'

services:
  redis:
    image: redis:latest@sha256:f957ce918b51f3ac10414244bedd0043c47db44a819f98b9902af1bd9d0afcea
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    ports:
      - "8000:8000"
    container_name: unixbot
    volumes:
      - ./config.ini:/app/config.ini
    depends_on:
      - redis