version: '3.8'

services:
  redis:
    image: redis:latest@sha256:541209804a009ab69e97a06504706cfe83be2693150885fa08ed05a91f243089
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    container_name: unixbot
    environment:
      - REDIS_HOST=redis
      - TWITTER_USERNAME=bot_unixporn
      - TWITTER_PASSWORD=strongPassword
      - REDDIT_USERNAME=bot_unixporn
      - REDDIT_PASSWORD=strongPassword
      - REDDIT_CLIENT_ID=client_id
      - REDDIT_CLIENT_SECRET=client_secret
    depends_on:
      - redis