version: '3.8'

services:
  redis:
    image: redis:latest@sha256:541209804a009ab69e97a06504706cfe83be2693150885fa08ed05a91f243089
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    container_name: unixbot
    environment:
      - REDIS_HOST=redis
      - TWITTER_USERNAME=bot_unixporn
      - TWITTER_PASSWORD=AnsYTB%VA&QC8#E@UZEp
      - REDDIT_USERNAME=xShd0wX
      - REDDIT_PASSWORD=ciDmT8NN7PBHc9Lx7eBa
      - REDDIT_CLIENT_ID=NzIcriEocSFZHg
      - REDDIT_CLIENT_SECRET=AbQRGIUlx3arUQKnbv4tDOb_8NM
      - DRIVER_TIMEOUT=60
    volumes:
      - ./_tmp:/app/screenshot
    depends_on:
      - redis