version: '3.8'

services:
  redis:
    image: redis:latest@sha256:1b835e5a8d5db58e8b718850bf43a68ef5a576fc68301fd08a789b20b4eecb61
    container_name: redis
    ports:
      - "6379:6379"
  unixbot:
    image: unixbot
    container_name: unixbot
    environment:
      - REDIS_HOST=redis
      - TWITTER_USERNAME=bot_unixporn
      - TWITTER_PASSWORD=strongPassword
      - REDDIT_USERNAME=bot_unixporn
      - REDDIT_PASSWORD=strongPassword
      - REDDIT_CLIENT_ID=client_id
      - REDDIT_CLIENT_SECRET=client_secret
    depends_on:
      - redis