---
name: "Sync labels"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/labels.yaml"]

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Sync Labels
        uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # renovate: tag=v2.3.2
        with:
          config-file: .github/labels.yaml
          token: "${{ secrets.CI_BOT_TOKEN }}"
          delete-other-labels: false